### ISSUE TITLE
Conflict between macro and function

### ISSUE THREAD

**Issue by kolmogorov42** [Mikejmoffitt/LICS#2]
I'm using [SGDK](https://github.com/Stephane-D/SGDK) via [gendev](https://github.com/kubilus1/gendev) under a Vagrant Ubuntu VM on Windows 10 to compile LICS.

When cdaudio.c is being compiled during the build process, both stdlib.h and maths.h, one of Stéphane's headers, are included. Line 63 of stdlib.h passes `abs` as an argument to `_EXFUN`, which expects a function. However, `abs` is also defined as a macro in maths.h, therefore resulting in a macro expansion and an error.

I managed to compile the game without further problems by commenting out Stéphane's macro in his header, but this hardly seems ideal. Am I missing something? It's unlikely no-one else bumped into this.

Small matters aside, excellent job on the port. Looking forward to be able to beat the game on the Genesis!

**Comment by Mikejmoffitt** [comment]
Thanks for the report.

I haven't encountered this issue, but as I've always been faced with annoying troubles getting gcc to build properly, I've been using my own frozen binary copies of SDGK and the build chain for a while, hosted here:

https://csh.rit.edu/~moffitt/gendev

So, I probably just don't have the conflict because my stuff is super out of date. I may try building it again to test this against something more modern, and I'll let you know how it goes.

**Comment by Mikejmoffitt** [comment]
I've updated my toolchain now, and I'm seeing the same issue. Unfortunately, I think this is really a problem to be reported at https://github.com/kubilus1/gendev. It might be good to create a patch that can be applied to either SGDK or to stdlib.h to resolve the issue.
